charts/urls.py
from django.urls import path
from charts import views
from .views import AllView, MovieView, BookView, GameView

app_name = 'charts'

urlpatterns = [
    path('all-statistics', AllView.as_view(), name='charts'),
    path('all-count', views.all_count, name='all_count'),
    path('all-ratings', views.all_ratings, name='all_ratings'),
    path('movies', MovieView.as_view(), name='movie'),
    path('movies-chart', views.movies_chart, name='movies_charts'),
    path('movies-rating', views.movies_ratings, name='movies_ratings'),
    path('movies-director', views.movies_directors, name='movies_directors'),
    path('movies-release', views.movies_release_years, name='movies_release'),
    path('books', BookView.as_view(), name='book'),
    path('books-chart', views.books_chart, name='books_charts'),
    path('books-rating', views.books_ratings, name='books_ratings'),
    path('books-author', views.books_authors, name='books_authors'),
    path('books-release', views.books_release_years, name='books_release'),
    path('games', GameView.as_view(), name='game'),
    path('games-chart', views.games_chart, name='games_charts'),
    path('games-rating', views.games_ratings, name='games_ratings'),
    path('games-studio', views.games_studio, name='games_studio'),
    path('games-release', views.games_release_years, name='games_release'),
]

shelfy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import MediaSearchView, MediaDetailView, home_view, SearchSuggestionsView, books_view, movies_view, games_view, media_detail_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user_management.urls')),
    path('library/', include('user_library.urls')),
    path('socials/', include('socials.urls')),
    path('statistics/', include('charts.urls', namespace ='statistics')),
    # Home page URLs
    path('', home_view, name='home'),
    path('home/', home_view, name='home_alt'),

    # Search and detail URLs
    path('search/', MediaSearchView.as_view(), name='media_search'),
    path('<str:media_type>/<str:external_id>/',
         MediaDetailView.as_view(), name='media_detail'),

    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='user_management/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='user_management/password_reset/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user_management/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user_management/password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user_management/password_reset/password_reset_complete.html'), name='password_reset_complete'),


   # API endpoints for modal views
    path('api/media/<str:media_type>/<str:external_id>/', media_detail_api, name='media_detail_api'),

    path('books/', books_view, name='books'),
    path('movies/', movies_view, name='movies'),
    path('games/', games_view, name='games'),

]

templates/chartjs/games.html
{% extends 'base.html' %}
  
<head> 
  <meta charset="utf-8"> 
  <title>chartsjs</title> 
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> 
  
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
  
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
</head> 

{% block content %}

<!-- game Charts -->
 <div>
{% if game_count %}
  <div id="container text-center">
    <div class="row">
      <div class="col">
        <p class="text-center">Number of Games Played</p>
        <p class="text-center">{{ game_count }}</p>
      </div>
      <div class="col">
        <p class="text-center">Average Game Rating</p>
        <p class="text-center">{{ game_rating }} ★</p>
      </div>
    </div>
    
    <div class="row">
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="games_charts" data-url="{% url 'charts:games_charts' %}"></canvas>
        </div>
      </div>
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="games_ratings" data-url="{% url 'charts:games_ratings' %}"></canvas>
        </div>
      </div>
      
    </div>
    <div class="row">
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="games_studios" data-url="{% url 'charts:games_studio' %}"></canvas>
        </div>
      </div>
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="games_release" data-url="{% url 'charts:games_release' %}"></canvas>
        </div>
      </div>
    </div>
    
  </div>

 </div>
{% else %}
<p>Please rate a game first before viewing your statistics.</p>
{% endif %}

{% endblock content %}

  
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

  const ctx = document.getElementById('games_charts');
  $(function () {
    var $games_charts = $("#games_charts");

    console.log("Canvas found:", $games_charts[0]);
    
    $.ajax({
        url: $games_charts.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.genre) && Array.isArray(data.game)) {
            var ctx = $games_charts[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', ctx);
            console.log('Canvas element:', $games_charts[0]);

            // Initialize the chart
            new Chart(ctx, {
              type: 'horizontalBar',
              data: {
                labels: data.genre,
                datasets: [{
                  axis: 'y',
                  label: 'Games',
                  backgroundColor: 'blue',
                  data: data.game
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Top 10 Game Genres'
                },
                scales: {
                  xAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                }
              }
            });

          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // ratings chart
    const ratings = document.getElementById('games_ratings');
    $(function () {
    var $games_ratings = $("#games_ratings");

    console.log("Canvas found:", $games_ratings[0]);
    
    $.ajax({
        url: $games_ratings.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.rating) && Array.isArray(data.game)) {
            var rating = $games_ratings[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', rating);
            console.log('Canvas element:', $games_ratings[0]);

            // Initialize the chart
            new Chart(rating, {
              type: 'bar',
              data: {
                labels: data.rating,
                datasets: [{
                  label: 'Games',
                  backgroundColor: 'blue',
                  data: data.game
                }]
              },
              options: {
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Game Ratings'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                }
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // studios chart
    const studios = document.getElementById('games_studios');
    $(function () {
    var $games_studios = $("#games_studios");

    console.log("Canvas found:", $games_studios[0]);
    
    $.ajax({
        url: $games_studios.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.studio) && Array.isArray(data.game)) {
            var studio = $games_studios[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', studio);
            console.log('Canvas element:', $games_studios[0]);

            // Initialize the chart
            new Chart(studio, {
              type: 'bar',
              data: {
                labels: data.studios,
                datasets: [{
                  label: 'Games',
                  backgroundColor: 'blue',
                  data: data.game
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Game Studio/Developer'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                },
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // scatter chart for release year
    const release_year = document.getElementById('games_release');
    $(function () {
    var $games_release = $("#games_release");

    console.log("Canvas found:", $games_release[0]);
    
    $.ajax({
        url: $games_release.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.release_year) && Array.isArray(data.game)) {
            var release_year = $games_release[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', release_year);
            console.log('Canvas element:', $games_release[0]);

            // Initialize the chart
            new Chart(release_year, {
              type: 'bar',
              data: {
                labels: data.release_year,
                datasets: [{
                  label: 'games',
                  backgroundColor: 'blue',
                  data: data.game
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Game Release Years'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                },
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });
</script>
{% endblock scripts %}

templates/chartjs/movies.html
{% extends 'base.html' %}
  
<head> 
  <meta charset="utf-8"> 
  <title>chartsjs</title> 
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> 
  
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
  
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> 
</head> 

{% block content %}

<!-- Movie Charts -->
 <div>
{% if movie_count %}

  <div id="container text-center">
    <div class="row">
      <div class="col">
        <p class="text-center">Number of Movies Watched</p>
        <p class="text-center">{{ movie_count }}</p>
      </div>
      <div class="col">
        <p class="text-center">Average Movie Rating</p>
        <p class="text-center">{{ movie_rating }} ★</p>
      </div>
    </div>
    
    <div class="row">
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="movies_charts" data-url="{% url 'charts:movies_charts' %}"></canvas>
        </div>
      </div>
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="movies_ratings" data-url="{% url 'charts:movies_ratings' %}"></canvas>
        </div>
      </div>
      
    </div>
    <div class="row">
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="movies_directors" data-url="{% url 'charts:movies_directors' %}"></canvas>
        </div>
      </div>
      <div class="col">
        <div id="container" style="width: 100%;">
          <canvas id="movies_release" data-url="{% url 'charts:movies_release' %}"></canvas>
        </div>
      </div>
    </div>
    
  </div>

 </div>
 {% else %}
 <p>Please rate a movie first before viewing your statistics.</p>
 {% endif %}

{% endblock content %}

  
{% block scripts %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>

  const ctx = document.getElementById('movies_charts');
  $(function () {
    var $movies_charts = $("#movies_charts");

    console.log("Canvas found:", $movies_charts[0]);
    
    $.ajax({
        url: $movies_charts.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.genre) && Array.isArray(data.movie)) {
            var ctx = $movies_charts[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', ctx);
            console.log('Canvas element:', $movies_charts[0]);

            // Initialize the chart
            var movieChart = new Chart(ctx, {
              type: 'horizontalBar',
              data: {
                labels: data.genre,
                datasets: [{
                  axis: 'y',
                  label: 'Movies',
                  backgroundColor: 'blue',
                  data: data.movie
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Top 10 Movie Genres'
                },
                scales: {
                  xAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                }
              }
            });

          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // ratings chart
    const ratings = document.getElementById('movies_ratings');
    $(function () {
    var $movies_ratings = $("#movies_ratings");

    console.log("Canvas found:", $movies_ratings[0]);
    
    $.ajax({
        url: $movies_ratings.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.rating) && Array.isArray(data.movie)) {
            var rating = $movies_ratings[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', rating);
            console.log('Canvas element:', $movies_ratings[0]);

            // Initialize the chart
            new Chart(rating, {
              type: 'bar',
              data: {
                labels: data.rating,
                datasets: [{
                  label: 'Movies',
                  backgroundColor: 'blue',
                  data: data.movie
                }]
              },
              options: {
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Movie Ratings'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                }
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // directors chart
    const directors = document.getElementById('movies_directors');
    $(function () {
    var $movies_directors = $("#movies_directors");

    console.log("Canvas found:", $movies_directors[0]);
    
    $.ajax({
        url: $movies_directors.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.director) && Array.isArray(data.movie)) {
            var director = $movies_directors[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', director);
            console.log('Canvas element:', $movies_directors[0]);

            // Initialize the chart
            new Chart(director, {
              type: 'bar',
              data: {
                labels: data.directors,
                datasets: [{
                  label: 'Movies',
                  backgroundColor: 'blue',
                  data: data.movie
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Movie Directors'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                },
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });

    // scatter chart for release year
    const release_year = document.getElementById('movies_release');
    $(function () {
    var $movies_release = $("#movies_release");

    console.log("Canvas found:", $movies_release[0]);
    
    $.ajax({
        url: $movies_release.data("url"),
        success: function (data) {
          console.log('AJAX data:', data);  // Debug: Check if data is correct

          // Check if data exists and is in the expected format
          if (data && Array.isArray(data.release_year) && Array.isArray(data.movie)) {
            var release_year = $movies_release[0].getContext("2d");

            // Log to ensure that the context is set up correctly
            console.log('Canvas context:', release_year);
            console.log('Canvas element:', $movies_release[0]);

            // Initialize the chart
            new Chart(release_year, {
              type: 'bar',
              data: {
                labels: data.release_year,
                datasets: [{
                  label: 'Movies',
                  backgroundColor: 'blue',
                  data: data.movie
                }]
              },
              options: {
                indexAxis: 'y',
                responsive: true,
                legend: {
                  position: 'top',
                },
                title: {
                  display: true,
                  text: 'Movie Release Years'
                },
                scales: {
                  yAxes: [{
                      ticks: {
                          beginAtZero: true,
                          precision: 0
                      }
                  }]
                },
              }
            });
          } else {
            console.error('Invalid data format:', data);
          }
        },
        error: function (err) {
          console.error("Error fetching data", err);
        }
      });
    });
</script>
{% endblock scripts %}