charts/urls.py
from django.urls import path
from charts import views
from .views import AllView, MovieView, BookView, GameView

app_name = 'charts'

urlpatterns = [
    path('all-statistics', AllView.as_view(), name='charts'),
    path('all-count', views.all_count, name='all_count'),
    path('all-ratings', views.all_ratings, name='all_ratings'),
    path('movies', MovieView.as_view(), name='movie'),
    path('movies-chart', views.movies_chart, name='movies_charts'),
    path('movies-rating', views.movies_ratings, name='movies_ratings'),
    path('movies-director', views.movies_directors, name='movies_directors'),
    path('movies-release', views.movies_release_years, name='movies_release'),
    path('books', BookView.as_view(), name='book'),
    path('books-chart', views.books_chart, name='books_charts'),
    path('books-rating', views.books_ratings, name='books_ratings'),
    path('books-author', views.books_authors, name='books_authors'),
    path('books-release', views.books_release_years, name='books_release'),
    path('games', GameView.as_view(), name='game'),
    path('games-chart', views.games_chart, name='games_charts'),
    path('games-rating', views.games_ratings, name='games_ratings'),
    path('games-studio', views.games_studio, name='games_studio'),
    path('games-release', views.games_release_years, name='games_release'),
]

shelfy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import MediaSearchView, MediaDetailView, home_view, SearchSuggestionsView, books_view, movies_view, games_view, media_detail_api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user_management.urls')),
    path('library/', include('user_library.urls')),
    path('socials/', include('socials.urls')),
    path('statistics/', include('charts.urls', namespace ='statistics')),
    # Home page URLs
    path('', home_view, name='home'),
    path('home/', home_view, name='home_alt'),

    # Search and detail URLs
    path('search/', MediaSearchView.as_view(), name='media_search'),
    path('<str:media_type>/<str:external_id>/',
         MediaDetailView.as_view(), name='media_detail'),

    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='user_management/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Password reset URLs
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='user_management/password_reset/password_reset_form.html'), name='password_reset_form'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user_management/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user_management/password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user_management/password_reset/password_reset_complete.html'), name='password_reset_complete'),


   # API endpoints for modal views
    path('api/media/<str:media_type>/<str:external_id>/', media_detail_api, name='media_detail_api'),

    path('books/', books_view, name='books'),
    path('movies/', movies_view, name='movies'),
    path('games/', games_view, name='games'),

]

socials/urls.py
from django.urls import path
from . import views

app_name = 'socials'

urlpatterns = [
    # path('lobby/', views.lobby, name='lobby'), #to remove
    path('', views.chat, name='chat'),
    path('create-message/', views.create_message, name='create-message'),
    path('stream-chat-messages/', views.stream_chat_messages, name='stream-chat-messages'),
]

templates/chat.html
{% extends 'base.html' %}

{% block content %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chat</title>
    <style>


      .messages {
        background: #ffffff;
        border-radius: 8px;
        padding: 20px;
        margin-bottom: 30px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        font-size: 16px;
        height: 50vh;
        overflow-y: scroll;
      }

      .message {
        border-bottom: 1px solid #ced6e0;
        padding: 15px 0;
      }

      .message:last-child {
        border-bottom: none;
      }

      form {
        display: flex;
        flex-direction: column;
      }

      textarea,
      input,
      button {
        margin-bottom: 15px;
        padding: 15px;
        border: 1px solid #ced6e0;
        border-radius: 6px;
        font-size: 16px;
      }

      .message-box {
        background: rgba(247, 248, 245, 0.42);
        border-left: 4px solid #2D336B;
        margin-bottom: 15px;
        padding: 10px 15px;
        border-radius: 6px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }

      .message-author {
        font-weight: bold;
        margin-bottom: 5px;
      }

      .message-content {
        font-size: 16px;
        line-height: 1.4;
      }

      textarea {
        background: #f8f9fa;
        border: 1px solid #ced4da;
        box-sizing: border-box;
        width: 100%;
        padding: 12px 20px;
        border-radius: 6px;
        min-height: 100px;
        font-size: 16px;
        line-height: 1.5;
        resize: none;
        outline: none;
      }
    </style>
    <style>
      [x-cloak] {
        display: none !important;
      }
    </style>
  </head>

  <body>
    <div class="header">
      <h1>Welcome {{ user }}</h1>
    </div>

    <div class="container">
      <div class="messages">
        <div id="sse-data"></div>
      </div>

      <form
        x-cloak
        @submit.prevent="submit"
        x-data="{state: 'composing', errors: {}}"
      >
        <div>
          <textarea
            name="content"
            @input="state = 'composing'"
            autofocus
            placeholder="Your next message..."
          ></textarea>
          <button class="btn btn-primary">Send</button>
        </div>

        <div x-show="state === 'error'">
          <p>Error sending your message ❌</p>
        </div>
      </form>
    </div>

    <script>
      let eventSource
      const sseData = document.getElementById('sse-data')

      function startSSE() {
        eventSource = new EventSource("{% url 'socials:stream-chat-messages' %}")
        eventSource.onmessage = (event) => {
          const data = JSON.parse(event.data)
          const messageHTML = `
                    <div class="message-box">
                        <div class="message-author">${data.author__display_name}</div>
                        <div class="message-content">${data.content}</div>
                    </div>`
          sseData.innerHTML += messageHTML
        }
      }

      // On load, start SSE if the browser supports it.
      if (typeof EventSource !== 'undefined') {
        startSSE()
      } else {
        sseData.innerHTML =
          "Whoops! Your browser doesn't receive server-sent events."
      }
    </script>

    <script>
      function submit(event) {
        event.preventDefault()
        const formData = new FormData(event.target)

        const endpointUrl = "{% url 'socials:create-message' %}"
        fetch(endpointUrl, {
          method: 'post',
          body: formData,
          headers: {
            'X-CSRFToken': '{{ csrf_token }}',
          },
        })
          .then((response) => {
            this.state = response.ok ? 'success' : 'error'
            return response.json()
          })
          .then((data) => {
            this.errors = data.errors || {}
          })
      }
    </script>
    <script
      defer=""
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.12.3/dist/cdn.min.js"
    ></script>
  </body>
</html>
{% endblock content %}